FRS/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from dashing.utils import router as dashing_routes

from FRS import views
from api import FRSApi
from api.resources import TeamResource, EventResource

api_v1 = FRSApi(api_name='v1')
api_v1.register(TeamResource())
api_v1.register(EventResource())

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('TBAW.urls')),
    url(r'^', include('leaderboard.urls')),
    url(r'^$', views.landing, name='landing'),
    url(r'^s/', views.search, name='search'),
    url(r'^s2/', views.search_api, name='search_api'),
    url(r'^api/', include(api_v1.urls)),
    url(r'^api/', include('api.urls')),
    url(r'^l/', include('leaderboard2.urls')),
    url(r'^dashboard/', include(dashing_routes.urls)),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += [
    url(r'^plate/', include('django_spaghetti.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

TBAW/urls.py
from TBAW import views
from django.conf.urls import url

from FRS.config.tba import urls as tba_urls

urlpatterns = [
    url(tba_urls.TEAMS().urlpattern, views.team_view, name="team_view"),
    url(tba_urls.EVENTS().urlpattern, views.event_view, name="event_view"),
    url(r'^a/(?P<team1>[0-9]+)/(?P<team2>[0-9]+)/(?P<team3>[0-9]+)/', views.alliance_view, name="alliance_view")
]

TBAW/models.py
from django.db import models
from polymorphic.models import PolymorphicModel
from util.computations import average_match_score
from .ranking_models import RankingModel
from .scoring_models import ScoringModel

MAX_NAME_LENGTH = 120
MAX_DESCRIPTION_LENGTH = 500


class Team(models.Model):
    website = models.URLField(null=True)
    name = models.TextField()  # longer name

    locality = models.CharField(max_length=MAX_NAME_LENGTH, null=True)  # e.g. city
    region = models.CharField(max_length=MAX_NAME_LENGTH, null=True)  # e.g. state, province
    country_name = models.CharField(max_length=MAX_NAME_LENGTH, null=True)
    location = models.CharField(max_length=MAX_DESCRIPTION_LENGTH, null=True)  # full city + state + country

    team_number = models.PositiveSmallIntegerField()
    key = models.CharField(max_length=8)  # e.g. frc2791
    nickname = models.CharField(max_length=MAX_NAME_LENGTH)  # shorter name
    rookie_year = models.PositiveSmallIntegerField(null=True)
    motto = models.TextField(null=True)

    def __str__(self):
        return "{0} ({1})".format(self.nickname, self.team_number)

    @classmethod
    def create(cls, website, name, locality, region, country_name, location, team_number, key, nickname, rookie_year,
               motto):
        team = cls(website=website, name=name, locality=locality, region=region, country_name=country_name,
                   location=location, team_number=team_number, key=key, nickname=nickname, rookie_year=rookie_year,
                   motto=motto)
        return team


class Alliance(models.Model):
    # is this necessary? idk
    color_choices = (
        ('Red', 'Red'),
        ('Blue', 'Blue')
    )
    teams = models.ManyToManyField(Team)
    color = models.CharField(max_length=4, choices=color_choices, null=True)
    seed = models.SmallIntegerField(default=0, null=True)

    def __str__(self):
        return "(Seed #{1}) {0}".format(self.teams.all(), self.seed)

    def __repr__(self):
        return "(Seed #{1}) {0}".format(self.teams.all(), self.seed)


class Event(models.Model):
    key = models.CharField(max_length=10)  # e.g. 2016cmp
    name = models.CharField(max_length=MAX_DESCRIPTION_LENGTH)  # e.g. Finger Lakes Regional
    short_name = models.CharField(null=True, max_length=MAX_NAME_LENGTH)  # e.g. Finger Lakes
    event_code = models.CharField(max_length=7)  # e.g. cmp

    """https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/event_type.py"""
    event_type_choices = (
        (0, 'Regional'),
        (1, 'District'),
        (2, 'District Championship'),
        (3, 'Championship Division'),
        (4, 'Championship Finals'),
        (99, 'Offseason'),
        (100, 'Preseason'),
        (-1, 'Unlabeled')
    )
    event_type = models.SmallIntegerField(choices=event_type_choices, null=True)

    """https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/district_type.py#L6"""
    event_district_choices = (
        (0, 'No District'),
        (1, 'Michigan'),
        (2, 'Mid-Atlantic'),
        (3, 'New England'),
        (4, 'Pacific Northwest'),
        (5, 'Indiana'),
        (6, 'Chesapeake'),
        (7, 'North Carolina'),
        (8, 'Georgia'),
    )
    event_district = models.SmallIntegerField(choices=event_district_choices, null=True)

    year = models.PositiveSmallIntegerField()
    location = models.CharField(max_length=MAX_NAME_LENGTH, null=True)
    venue_address = models.TextField(null=True)
    timezone = models.CharField(max_length=20, null=True)
    website = models.URLField(null=True)
    official = models.BooleanField()
    teams = models.ManyToManyField(Team)
    alliances = models.ManyToManyField(Alliance)

    # webcast = my_webcast_model(), parse JSON data to model fields
    # district_points = my_district_points_model(), parse JSON data to model fields

    def __str__(self):
        return "Event {0}".format(self.key)

    def __repr__(self):
        return "Event {0}".format(self.key)

    def get_average_qual_match_score(self):
        return average_match_score(self.match_set.filter(comp_level__exact='qm'))

    def get_average_playoff_match_score(self):
        return average_match_score(self.match_set.filter(comp_level__in=['ef', 'qf', 'sf', 'f']))

    def get_average_overall_match_score(self):
        return average_match_score(self.match_set.all())


class Match(models.Model):
    key = models.CharField(max_length=20)  # yyyy{EVENT_CODE}_{COMP_LEVEL}m{MATCH_NUMBER}, e.g. 2016nyro_f1m2
    comp_level = models.CharField(max_length=6)  # e.g. qm, ef, qf, sf, f
    set_number = models.CharField(null=True, max_length=20)  # in 2016nyro_qf3m2, the set number is 3

    match_number = models.CharField(max_length=20)  # e.g. 2016nyro_qm20
    alliances = models.ManyToManyField(Alliance)
    # videos = my_videos_model, parse JSON data to model fields
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    # time_string = models.CharField(max_length=25)
    # time = models.DateTimeField(), parse UNIX timestamp to DatetimeField

    winner = models.ForeignKey(Alliance, null=True, related_name='winner')
    scoring_model = models.ForeignKey(ScoringModel, null=True)

    def __str__(self):
        return "Match {0}".format(self.key)

    def __repr__(self):
        return "Match {0}".format(self.key)


class Award(models.Model):
    name = models.CharField(max_length=MAX_NAME_LENGTH)

    # todo: https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/award_type.py#L15
    award_type_choices = ()

    award_type = models.CharField(choices=award_type_choices, max_length=MAX_NAME_LENGTH)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    # recipient = models.ForeignKey(Team, on_delete=models.CASCADE)
    year = models.PositiveSmallIntegerField()


class Robot(models.Model):
    key = models.CharField(max_length=13)  # e.g. frc2791_2016
    # team = models.ForeignKey(Team, on_delete=models.CASCADE)
    year = models.PositiveSmallIntegerField()
    name = models.CharField(max_length=MAX_NAME_LENGTH)

TBAW/views.py
from datetime import date

from django.db.models import F, Q
from annoying.decorators import render_to

from FRS.views import handle_404
from TBAW.models import Event, RankingModel, Team, ScoringModel, Alliance
from util.check import alliance_exists, team_exists
from util.getters import get_team, get_event, get_alliance


@render_to("TBAW/team_view.html")
def team_view(request, team_number):
    if Team.objects.filter(team_number=team_number).exists():
        team = get_team(team_number)
        events_this_year = Event.objects.prefetch_related('teams')\
            .filter(year=date.today().year, teams__team_number=team.team_number).order_by('end_date').values('key', 'year', 'name')

        return {
            'team': team,
            'events': events_this_year,
            'awards_count': team.awards_count,
            'blue_banners_count': team.blue_banners_count,
        }
    else:
        return handle_404(request)


@render_to('TBAW/event_view.html')
def event_view(request, event_key):
    if Event.objects.filter(key=event_key).exists():
        event = get_event(event_key)
        matches = event.match_set.all()

        def create_team_map(t: Team):
            return {
                'team_number': t.team_number,
                'label': str(t)
            }

        #
        # Optimizations here rely on lookup tables which may use an *excessive* amount of memory to load this page, to
        # offload this task of caching to the Django ORM, we may be able to change queries to use select_related and
        # prefetch_related.
        #

        # Assembling Alliances Lookup Table
        alliance_ids = [m.red_alliance_id for m in matches] + [m.blue_alliance_id for m in matches]
        alliances_by_id = {a.id: a for a in Alliance.objects.prefetch_related('teams').filter(id__in=alliance_ids)}
        alliances_by_match = {m: (alliances_by_id[m.red_alliance_id], alliances_by_id[m.blue_alliance_id])
                              for m in matches}

        # Dictionary matching Match instances to list of pairs of the form (team_number, string representation)
        matches_to_alliances = {
            m: (tuple(create_team_map(t) for t in alliances_by_match[m][0].teams.all()),
                tuple(create_team_map(t) for t in alliances_by_match[m][1].teams.all()))
                for m in matches}

        # Assembling Scoring Model Lookup Table
        scoring_model_ids = [m.scoring_model_id for m in matches]
        models = {m.id: m for m in ScoringModel.objects.filter(Q(id__in=scoring_model_ids)).all()}
        matches_to_scoring_models = {m: models[m.scoring_model_id] for m in matches}

        # Assemble RankingModel Lookup Table
        ranking_models = RankingModel.objects.select_related('event').filter(event__key=event_key).annotate(team_number=F('team__team_number')).all()
        ranking_models = {x.team_number: x for x in ranking_models}

        return {
            'event': event,
            'ranking_models': ranking_models,
            'matches': matches,
            'match_alliances': matches_to_alliances,
            'match_scorings': matches_to_scoring_models
        }
    else:
        return handle_404(request)


def alliance_view(request, team1: str, team2: str, team3: str):
    team1 = int(team1)
    team2 = int(team2)
    team3 = int(team3)

    if team_exists(team1):
        team1 = get_team(team1)
    if team_exists(team2):
        team2 = get_team(team2)
    if team_exists(team3):
        team3 = get_team(team3)

    if alliance_exists(team1, team2, team3):
        return alliance_exists_view(request, get_alliance(team1, team2, team3))
    else:
        return alliance_does_not_exist_view(request, [team1, team2, team3])


def alliance_view_alliance_obj(request, alliance_obj):
    teams = alliance_obj.teams.all()
    return alliance_view(request, teams[0].team_number, teams[1].team_number, teams[2].team_number)


@render_to('TBAW/alliance_exists.html')
def alliance_exists_view(request, alliance):
    events = Event.objects.filter(allianceappearance__alliance=alliance).order_by('-end_date')
    # wins = alliance.get_wins()
    # losses = alliance.get_losses()
    # ties = alliance.get_ties()

    return {
        'alliance': alliance,
        'events': events,
    }


@render_to('TBAW/alliance_does_not_exist.html')
def alliance_does_not_exist_view(request, teams):
    return {
        'teams': teams
    }

templates/TBAW/alliance_does_not_exist.html
{% extends 'FRS/base_template.html' %}

{% block body %}
    It looks like
    {% for item in teams %}{% if forloop.first %}{% else %}{% if forloop.last %} and {% else %}, {% endif %}{% endif %}
        {{ item }}{% endfor %} have never been an alliance together!
{% endblock %}

templates/TBAW/alliance_exists.html
{% extends 'FRS/base_template.html' %}
{% load humanize %}

{% block body %}
    <div class="uk-grid">
        <div class="uk-width-large-1-1 uk-container-center">
            <h2>{% for item in alliance.teams.all %}{% if not forloop.first %}{% if forloop.last %} and {% else %},
            {% endif %}{% endif %}<a href="{% url 'team_view' item.team_number %}">{{ item }}</a>{% endfor %}</h2>
        </div>
        <div class="uk-width-1-2">
            <h4>Rating: {{ alliance.elo_mu|floatformat:2 }} ({{ alliance.get_elo_standing|ordinal|intcomma }}
                overall)</h4>
        </div>
        <div class="uk-width-1-2">
            <h4 class="uk-text-right">First appeared in {{ events.first.year }}</h4>
        </div>
    </div>

    <p>
        Competed in {{ events.count }} event{{ events.count|pluralize }} all-time:
        {% for event in events %}
            <a href="{% url 'event_view' event.key %}">{{ event.name.strip }}
                {{ event.year }}{% if not forloop.last %},{% endif %}</a>
        {% endfor %}
    </p>

    <p>Played {{ alliance.match_set.count }} match{{ alliance.match_set.count|pluralize:"es" }} all-time
        ({{ alliance.get_record }}).</p>

{% endblock %}

templates/TBAW/event_view.html
{% extends 'FRS/base_template.html' %}
{% load humanizers %}
{% load getters %}
{% load math %}
{% block title %}{{ event.year }} {{ event.name }}{% endblock %}
{% block body %}
    <h1>{{ event.name }} {{ event.year }}</h1><br>
    {% if event.event_district != 0 %}
        Part of the {{ event.get_event_district_display }} District<br>
    {% endif %}
    <strong>{{ event.get_event_type_display }}</strong><br>
    <a href="https://www.google.com/maps/place/{{ event.location }}/">{{ event.location }}</a><br>
    {{ event.end_date }}<br>
    {% if event.website != None %}
        <a href="{{ event.website }}">{{ event.website }}</a>
    {% endif %}

    <table class="uk-table uk-table-condensed uk-table-hover">
        <caption>Teams in Attendance</caption>
        <thead>
        <tr>
            <th>Rank</th>
            <th>Team</th>
            <th>Team Number</th>
            <th>Event Record</th>
            <th>Pre-Event Elo</th>
            <th>Post-Event Elo</th>
            <th>Elo Change</th>
        </tr>
        </thead>
        <tbody>
        {% for team in event.teams.all %}
            {% with ranking_models|get_from_dict:team.team_number as rm %}
                <tr>
                    <td>{{ rm.rank }}</td>
                    <td><a href="{% url 'team_view' team.team_number %}">{{ team.nickname }}</a></td>
                    <td>{{ team.team_number }}</td>
                    <td>{{ rm.get_record }}</td>
                    <td>{{ rm.elo_mu_pre|floatformat:2 }}</td>
                    <td>{{ rm.elo_mu_post|floatformat:2 }}</td>
                    <td>{{ rm.elo_mu_post|subtract:rm.elo_mu_pre|floatformat:2 }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        </tbody>
    </table>

    <table class="uk-table uk-table-condensed" id="event-table">
        <caption>Matches</caption>
        <thead>
        <tr>
            <th>Match</th>
            <th>Red</th>
            <th>Blue</th>
            <th>Red Score</th>
            <th>Blue Score</th>
        </tr>
        </thead>
        <tbody>
        {% for match in matches %}
            <tr>
                <td>
                    {{ match.comp_level|match_humanize }}
                    {% if match.comp_level != 'qm' and match.comp_level != 'f' %}
                        Set {{ match.set_number }}
                    {% endif %}
                    Match {{ match.match_number }}
                </td>

                {% with match_alliances|get_from_dict:match as alliances %}
                    <td class="red-alliance">
                        {% with alliances.0 as red %}
                            <a href="{% url 'alliance_view' red.0.team_number red.1.team_number red.2.team_number %}">
                                {{ red.0.label }}<br>
                                {{ red.1.label }}<br>
                                {{ red.2.label }}
                            </a>
                        {% endwith %}
                    </td>
                    <td class="blue-alliance">
                        {% with alliances.1 as blue %}
                            <a href="{% url 'alliance_view' blue.0.team_number blue.1.team_number blue.2.team_number %}">
                                {{ blue.0.label }}<br>
                                {{ blue.1.label }}<br>
                                {{ blue.2.label }}
                            </a>
                        {% endwith %}</td>
                {% endwith %}
                {% with match_scorings|get_from_dict:match as scoring_model %}
                    <td class="red-alliance">{{ scoring_model.red_total_score }}</td>
                    <td class="blue-alliance">{{ scoring_model.blue_total_score }}</td>
                {% endwith %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/TBAW/team_view.html
{% extends 'FRS/base_template.html' %}
{% load humanize %}
{% block title %}Team {{ team.team_number }} - {{ team.nickname }}{% endblock %}
{% block body %}
    <div class="uk-grid">
        <div class="uk-width-large-1-1 uk-container-center">
            <h2>Team {{ team.team_number }} - {{ team.nickname }}</h2>
        </div>
        <div class="uk-width-1-2">
            <h4>Rating: {{ team.elo_mu|floatformat:2 }} ({{ team.get_elo_standing|ordinal|intcomma }} overall)</h4>
        </div>
        <div class="uk-width-1-2"><h4 class="uk-text-right">Rookie year: {{ team.rookie_year }}</h4></div>
        <div class="uk-width-1-2"><h4>All-time Record: {{ team.get_record }} ({{ team.get_winrate|floatformat:-2 }}%
            winrate)</h4></div>
        <div class="uk-width-1-2"><h4 class="uk-text-right">
            <a href="https://www.google.com/maps/place/{{ team.location }}/">{{ team.location }}</a>
        </h4></div>
    </div>

    <p>
        Won {{ awards_count }} award{{ awards_count|pluralize }} all-time{% if awards_count > 0 %}, with
        {{ blue_banners_count }} blue banners:
        <ul class="uk-list">
            {% with team.count_awards.items as award_items %}
            {% for award in award_items %}
                <li>&bull; {{ award.1|length }}x {{ award.0 }} at {% for event in award.1 %}
                    <a href="{% url 'event_view' event.key %}">
                        {{ event.name.strip }} {{ event.year }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
                </li>
            {% endfor %}
            {% endwith %}
        </ul>
    {% else %}.
    {% endif %}
{% endblock %}